# Host to use for canonical URL generation (without trailing slash)
host: https://docs.cloud.service.gov.uk

# Header-related options
show_govuk_logo: true
service_name: Platform as a Service
service_link: https://www.cloud.service.gov.uk
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://www.cloud.service.gov.uk
  Get started: https://www.cloud.service.gov.uk/get-started
  Features: https://www.cloud.service.gov.uk/features
  Documentation: /
  Support: https://www.cloud.service.gov.uk/support

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id: UA-43115970-5

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

enable_search: true
